# fleet-gitops/secret-provider-class.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fleet-db-credentials-spc # A single, clear name
  namespace: fleet-dev
spec:
  provider: aws
  parameters:
    objectName: "fleet-dev-db-credentials" # The name of the secret in AWS
    objectType: "secretsmanager"
  # This section tells the driver to create a native Kubernetes secret
  secretObjects:
  - secretName: fleet-db-secret # The K8s secret to create
    type: Opaque
    data:
      # Map the keys from the AWS JSON secret to keys in the K8s secret
      - key: DB_USERNAME
        objectName: username # 'username' is the key in your AWS secret's JSON
      - key: DB_PASSWORD
        objectName: password
      - key: DB_HOST
        objectName: host
      - key: DB_PORT
        objectName: port
      - key: DB_NAME
        objectName: dbname