# fleet-gitops/secret-provider.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fleet-db-credentials-spc
  namespace: fleet-dev
spec:
  provider: aws
  parameters:
    objectName: "fleet-dev-db-credentials" # The name of the secret in AWS Secrets Manager
    objectType: "secretsmanager"