# fleet-gitops/sync-secret.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fleet-db-credentials-spc
  namespace: fleet-dev
spec:
  provider: aws
  parameters:
    objectName: "fleet-dev-db-credentials"
    objectType: "secretsmanager"
  secretObjects:
  - secretName: fleet-db-secret
    type: Opaque
    data:
    - key: DB_USERNAME
      objectName: username
    - key: DB_PASSWORD
      objectName: password
    - key: DB_HOST
      objectName: host
    - key: DB_PORT
      objectName: port
    - key: DB_NAME
      objectName: dbname